#pragma once

static const char *HTML_PAGE =
"<!DOCTYPE html>"
"<html lang='vi'>"
"<head>"
"<meta charset='UTF-8'>"
"<meta name='viewport' content='width=device-width, initial-scale=1.0'>"
"<title>ESP32 WiFi Setup</title>"
"<style>"
"*{margin:0;padding:0;box-sizing:border-box}"
"body{"
"font-family:'Segoe UI',Tahoma,Geneva,Verdana,sans-serif;"
"background:linear-gradient(135deg,#667eea 0%,#764ba2 100%);"
"min-height:100vh;"
"display:flex;"
"justify-content:center;"
"align-items:center;"
"padding:20px"
"}"
".container{"
"background:white;"
"border-radius:20px;"
"box-shadow:0 20px 60px rgba(0,0,0,0.3);"
"padding:40px;"
"max-width:400px;"
"width:100%;"
"animation:slideIn 0.5s ease-out"
"}"
"@keyframes slideIn{"
"from{opacity:0;transform:translateY(-30px)}"
"to{opacity:1;transform:translateY(0)}"
"}"
".logo{"
"text-align:center;"
"margin-bottom:30px"
"}"
".logo svg{"
"width:80px;"
"height:80px;"
"fill:#667eea"
"}"
"h1{"
"color:#333;"
"text-align:center;"
"margin-bottom:10px;"
"font-size:28px"
"}"
".subtitle{"
"text-align:center;"
"color:#666;"
"margin-bottom:30px;"
"font-size:14px"
"}"
".form-group{"
"margin-bottom:25px"
"}"
"label{"
"display:block;"
"color:#555;"
"font-weight:600;"
"margin-bottom:8px;"
"font-size:14px"
"}"
"input[type='text'],input[type='password']{"
"width:100%;"
"padding:12px 15px;"
"border:2px solid #e0e0e0;"
"border-radius:10px;"
"font-size:15px;"
"transition:all 0.3s;"
"outline:none"
"}"
"input[type='text']:focus,input[type='password']:focus{"
"border-color:#667eea;"
"box-shadow:0 0 0 3px rgba(102,126,234,0.1)"
"}"
"input[type='submit']{"
"width:100%;"
"padding:14px;"
"background:linear-gradient(135deg,#667eea 0%,#764ba2 100%);"
"color:white;"
"border:none;"
"border-radius:10px;"
"font-size:16px;"
"font-weight:600;"
"cursor:pointer;"
"transition:all 0.3s;"
"margin-top:10px"
"}"
"input[type='submit']:hover{"
"transform:translateY(-2px);"
"box-shadow:0 10px 20px rgba(102,126,234,0.4)"
"}"
"input[type='submit']:active{"
"transform:translateY(0)"
"}"
".info{"
"background:#f8f9fa;"
"padding:15px;"
"border-radius:10px;"
"margin-top:20px;"
"text-align:center"
"}"
".info p{"
"color:#666;"
"font-size:13px;"
"margin:5px 0"
"}"
".status{"
"display:inline-block;"
"width:8px;"
"height:8px;"
"background:#4caf50;"
"border-radius:50%;"
"margin-right:5px;"
"animation:pulse 2s infinite"
"}"
"@keyframes pulse{"
"0%,100%{opacity:1}"
"50%{opacity:0.5}"
"}"
"</style>"
"</head>"
"<body>"
"<div class='container'>"
"<div class='logo'>"
"<svg viewBox='0 0 24 24'>"
"<path d='M1,9L12,1L23,9V23H1V9M5,13V19H19V13H5M7,15H9V17H7V15M11,15H13V17H11V15M15,15H17V17H15V15Z'/>"
"</svg>"
"</div>"
"<h1>ESP32 WiFi</h1>"
"<p class='subtitle'>Cấu hình kết nối mạng</p>"
"<form action='/wifi' method='post'>"
"<div class='form-group'>"
"<label for='ssid'>🌐 Tên WiFi (SSID)</label>"
"<input type='text' id='ssid' name='ssid' placeholder='Nhập tên WiFi' required>"
"</div>"
"<div class='form-group'>"
"<label for='pass'>🔒 Mật khẩu</label>"
"<input type='password' id='pass' name='pass' placeholder='Nhập mật khẩu WiFi' required>"
"</div>"
"<div class='form-group'>"
"<label for='token'>🔑 Device Token</label>"
"<input type='text' id='token' name='token' placeholder='Nhập token thiết bị (tùy chọn)'>"
"</div>"
"<input type='submit' value='💾 Lưu cấu hình'>"
"</form>"
"<div class='info'>"
"<p><span class='status'></span>Chế độ AP đang hoạt động</p>"
"<p>SSID: <strong>ESP32_SETUP</strong></p>"
"<p>Password: <strong>12345678</strong></p>"
"</div>"
"</div>"
"</body>"
"</html>";
